### ISSUE TITLE
可视化实验补充

### ISSUE THREAD

**Issue by zbxC3H6** [ZhangWeihang99/HVSA#5]
作者您好，我看完了您的论文，其中关于KEA模块表现实验，以及后续的与GaLR的可视化对比试验部分并没有出现在代码中，您可以考虑上传一下可视化验证的代码吗？谢谢。

**Comment by ZhangWeihang99** [comment]
1. 关于KEA模块：可视化实验收到了这个 [仓库](https://github.com/frgfm/torch-cam) 的启发
2. 关于对比实验：在代码eval.py中，矩阵 $sims$ 包含了测试集所有图文对的相似度。
---
Regarding the KEA module: The visualization experiments were inspired by this [repository](https://github.com/frgfm/torch-cam).
Regarding the comparative experiment: In the eval.py code, the matrix $sims$ contains the similarities of all image-text pairs in the test set.
