### ISSUE TITLE
关于数据集放的位置

### ISSUE THREAD

**Issue by BigShow5wang** [ZhangWeihang99/HVSA#7]
作者你好，我想请问一下，我从你给的链接里面下的数据集，是只需要image文件的图片吗？这个image文件夹我应该放在哪里？可以如下图所示这样子放吗
<img width="173" alt="20242236" src="https://github.com/user-attachments/assets/0d507eea-b79c-4ec6-86cc-a9107b887854">

**Comment by ZhangWeihang99** [comment]
以RSICD数据集为例，图中RSICD_images文件的路径应该由[HVSA_rsicd.yaml](https://github.com/ZhangWeihang99/HVSA/blob/main/configs/HVSA_rsicd.yaml)中的image_path 指定。
